# Generated by Django 4.0.4 on 2022-06-11 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_authuser_delete_authusergroups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='slika',
        ),
    ]
